
WorldFactory.AddState
(
	new Map.CellState
	{
		ID = 1,
		Name = "Rock",
		Permanent = true,
		Hard = true,
		Density = 2,
		DiffuseMap = "Textures\\rock",
		NormalMap = "Textures\\rock-normal",
		FootstepCue = "RockFootsteps",
		RubbleCue = "Rubble",
		SpecularPower = 200.0f,
		SpecularIntensity = 0.2f,
	},
	new Map.CellState
	{
		ID = 2,
		Name = "Temporary",
		Permanent = false,
		Hard = false,
		Density = 2,
		DiffuseMap = "Textures\\white",
		NormalMap = "Textures\\temporary-normal",
		FootstepCue = "TemporaryFootsteps",
		RubbleCue = "TemporaryRubble",
		SpecularPower = 250.0f,
		SpecularIntensity = 0.4f,
		Tint = new Vector3(0.3f, 0.5f, 0.7f),
	},
	new Map.CellState
	{
		ID = 3,
		Name = "AvoidAI",
		Permanent = true,
		Hard = true,
		Density = 2,
		DiffuseMap = "Textures\\dirty",
		NormalMap = "Textures\\dirty-normal",
		FootstepCue = "TemporaryFootsteps",
		RubbleCue = "TemporaryRubble",
		SpecularPower = 1.0f,
		SpecularIntensity = 0.0f,
		Tint = new Vector3(0.15f),
	},
	new Map.CellState
	{
		ID = 4,
		Name = "Dirt",
		Permanent = false,
		Hard = true,
		Density = 0.5f,
		DiffuseMap = "Textures\\dirt",
		NormalMap = "Textures\\dirt-normal",
		FootstepCue = "DirtFootsteps",
		RubbleCue = "DirtRubble",
		SpecularPower = 1.0f,
		SpecularIntensity = 0.0f,
	},
	new Map.CellState
	{
		ID = 6,
		Name = "Critical",
		Permanent = false,
		Hard = false,
		Density = 2,
		DiffuseMap = "Textures\\danger",
		NormalMap = "Textures\\plain-normal",
		FootstepCue = "CriticalFootsteps",
		RubbleCue = "CriticalRubble",
		SpecularPower = 1.0f,
		SpecularIntensity = 0.0f,
	},
	new Map.CellState
	{
		ID = 7,
		Name = "Foliage",
		Permanent = false,
		Hard = false,
		Density = 0.5f,
		DiffuseMap = "Textures\\foliage",
		NormalMap = "Textures\\plain-normal",
		FootstepCue = "FoliageFootsteps",
		RubbleCue = "FoliageRubble",
		SpecularPower = 1.0f,
		SpecularIntensity = 0.0f,
		AllowAlpha = true,
		Tiling = 3.0f,
	},
	new Map.CellState
	{
		ID = 8,
		Name = "Hard",
		Permanent = false,
		Hard = true,
		Density = 0.5f,
		DiffuseMap = "Textures\\dirty",
		NormalMap = "Textures\\metal-channels-normal",
		FootstepCue = "WoodFootsteps",
		RubbleCue = "WoodRubble",
		SpecularPower = 200.0f,
		SpecularIntensity = 0.2f,
		Tint = new Vector3(0.4f),
	},
	new Map.CellState
	{
		ID = 9,
		Name = "Floater",
		Permanent = false,
		Hard = true,
		Density = 0.1f,
		DiffuseMap = "Textures\\dirty",
		NormalMap = "Textures\\metal-channels-normal",
		FootstepCue = "WoodFootsteps",
		RubbleCue = "WoodRubble",
		SpecularPower = 1.0f,
		SpecularIntensity = 0.0f,
		Tint = new Vector3(0.9f, 0.3f, 0.0f),
	},
	new Map.CellState
	{
		ID = 12,
		Name = "Fragile",
		Permanent = false,
		Hard = false,
		Density = 0.5f,
		DiffuseMap = "Textures\\white",
		NormalMap = "Textures\\temporary-normal",
		FootstepCue = "TemporaryFootsteps",
		RubbleCue = "TemporaryRubble",
		SpecularPower = 250.0f,
		SpecularIntensity = 0.4f,
		Tint = new Vector3(0.8f, 1.0f, 0.2f),
	},
	// 13
	new Map.CellState
	{
		ID = 14,
		Name = "Neutral",
		Permanent = false,
		Hard = false,
		Density = 3,
		FootstepCue = "InfectedFootsteps",
		RubbleCue = "InfectedRubble",
		DiffuseMap = "Textures\\white",
		NormalMap = "Textures\\temporary-normal",
		SpecularPower = 250.0f,
		SpecularIntensity = 0.4f,
		Tint = new Vector3(1.0f, 0.8f, 0.2f),
	},
	new Map.CellState
	{
		ID = 18,
		Name = "Breakable",
		Permanent = false,
		Hard = false,
		Density = 1,
		DiffuseMap = "Textures\\white",
		NormalMap = "Textures\\temporary-normal",
		FootstepCue = "TemporaryFootsteps",
		RubbleCue = "TemporaryRubble",
		SpecularPower = 250.0f,
		SpecularIntensity = 0.4f,
		Tint = new Vector3(0.7f),
	},
	new Map.CellState
	{
		ID = 23,
		Name = "RockChunky",
		Permanent = true,
		Hard = true,
		Density = 2,
		DiffuseMap = "Textures\\rock-chunky",
		NormalMap = "Textures\\rock-chunky-normal",
		FootstepCue = "RockFootsteps",
		RubbleCue = "Rubble",
		SpecularPower = 1.0f,
		SpecularIntensity = 0.0f,
		Tiling = 0.25f,
	},
	new Map.CellState
	{
		ID = 30,
		Name = "White",
		Permanent = false,
		Hard = false,
		ShadowCast = false,
		Density = 0.5f,
		DiffuseMap = "Textures\\white",
		NormalMap = "Textures\\plain-normal",
		FootstepCue = "MetalFootsteps",
		RubbleCue = "MetalRubble",
		SpecularIntensity = 0.0f,
		Glow = true,
	},
	new Map.CellState
	{
		ID = 31,
		Name = "Metal",
		Permanent = true,
		Hard = true,
		Density = 1,
		DiffuseMap = "Textures\\dirty",
		NormalMap = "Textures\\metal-channels2-normal",
		FootstepCue = "MetalFootsteps",
		RubbleCue = "MetalRubble",
		SpecularPower = 200.0f,
		SpecularIntensity = 0.2f,
		Tint = new Vector3(0.25f),
	},
	new Map.CellState
	{
		ID = 32,
		Name = "MetalSwirl",
		Permanent = true,
		Hard = true,
		Density = 1,
		DiffuseMap = "Textures\\dirty",
		NormalMap = "Textures\\metal-swirl-normal",
		FootstepCue = "MetalFootsteps",
		RubbleCue = "MetalRubble",
		SpecularPower = 200.0f,
		SpecularIntensity = 0.2f,
		Tint = new Vector3(0.25f),
	},
	new Map.CellState
	{
		ID = 34,
		Name = "Invisible",
		Permanent = true,
		Hard = true,
		Invisible = true,
		AllowAlpha = true,
		Density = 1,
		FootstepCue = "WoodFootsteps",
		RubbleCue = "WoodRubble",
		DiffuseMap = "Textures\\debug",
		NormalMap = "Textures\\plain-normal",
	},
	new Map.CellState
	{
		ID = 35,
		Name = "WhitePermanent",
		Permanent = true,
		Hard = true,
		ShadowCast = false,
		Density = 0.5f,
		DiffuseMap = "Textures\\white",
		NormalMap = "Textures\\plain-normal",
		FootstepCue = "MetalFootsteps",
		RubbleCue = "MetalRubble",
		SpecularIntensity = 0.0f,
		Glow = true,
	},
	new Map.CellState
	{
		ID = 36,
		Name = "Debug",
		Permanent = true,
		Hard = true,
		Density = 1,
		FootstepCue = "MetalFootsteps",
		RubbleCue = "MetalRubble",
		DiffuseMap = "Textures\\debug",
		NormalMap = "Textures\\plain-normal",
		SpecularPower = 1.0f,
		SpecularIntensity = 0.0f
	},
	new Map.CellState
	{
		ID = 37,
		Name = "DebugTemporary",
		Permanent = false,
		Hard = true,
		Density = 1,
		FootstepCue = "WoodFootsteps",
		RubbleCue = "WoodRubble",
		DiffuseMap = "Textures\\debug2",
		NormalMap = "Textures\\plain-normal",
		SpecularPower = 1.0f,
		SpecularIntensity = 0.0f,
	},
	new Map.CellState
	{
		ID = 38,
		Name = "Powered",
		Permanent = false,
		Hard = false,
		Density = 2,
		DiffuseMap = "Textures\\powered",
		NormalMap = "Textures\\temporary-normal",
		FootstepCue = "TemporaryFootsteps",
		RubbleCue = "TemporaryRubble",
		SpecularPower = 250.0f,
		SpecularIntensity = 0.4f,
		Glow = true,
	},
	new Map.CellState
	{
		ID = 39,
		Name = "PermanentPowered",
		Permanent = false,
		Hard = true,
		Density = 2,
		DiffuseMap = "Textures\\powered-permanent",
		NormalMap = "Textures\\temporary-normal",
		FootstepCue = "TemporaryFootsteps",
		RubbleCue = "TemporaryRubble",
		SpecularPower = 250.0f,
		SpecularIntensity = 0.4f,
		Glow = true,
	},
	new Map.CellState
	{
		ID = 40,
		Name = "InfectedCritical",
		Permanent = false,
		Hard = true,
		Density = 3,
		FootstepCue = "InfectedFootsteps",
		RubbleCue = "InfectedRubble",
		DiffuseMap = "Textures\\white",
		NormalMap = "Textures\\temporary-normal",
		SpecularPower = 250.0f,
		SpecularIntensity = 0.4f,
		Tint = new Vector3(0.4f, 0.0f, 0.0f),
	},
	new Map.CellState
	{
		ID = 41,
		Name = "Infected",
		Permanent = false,
		Hard = false,
		Density = 3,
		FootstepCue = "InfectedFootsteps",
		RubbleCue = "InfectedRubble",
		DiffuseMap = "Textures\\white",
		NormalMap = "Textures\\temporary-normal",
		SpecularPower = 250.0f,
		SpecularIntensity = 0.4f,
		Tint = new Vector3(0.8f, 0.1f, 0.1f),
	},
	new Map.CellState
	{
		ID = 42,
		Name = "Black",
		Permanent = true,
		Hard = true,
		ShadowCast = true,
		Density = 0.5f,
		DiffuseMap = "Textures\\white",
		NormalMap = "Textures\\plain-normal",
		FootstepCue = "MetalFootsteps",
		RubbleCue = "MetalRubble",
		SpecularPower = 1.0f,
		SpecularIntensity = 0.0f,
		Tint = Vector3.Zero,
	}
);